// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tHGk1N9HgPC02oymF2rs3qEhducT_rg',
    appId: '1:513756595410:web:842e69c3a23f61cc4b590b',
    messagingSenderId: '513756595410',
    projectId: 'project-8a903',
    authDomain: 'project-8a903.firebaseapp.com',
    storageBucket: 'project-8a903.firebasestorage.app',
    measurementId: 'G-20XVJNC67G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6SPW-ypm6jlEIzlUuX-x196J3VhGwYgk',
    appId: '1:513756595410:android:34f1696b139dd8724b590b',
    messagingSenderId: '513756595410',
    projectId: 'project-8a903',
    storageBucket: 'project-8a903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6HjdyuU8wX4tuHnPqg7nt2sUa-aNGeY',
    appId: '1:513756595410:ios:93f2407d1084060d4b590b',
    messagingSenderId: '513756595410',
    projectId: 'project-8a903',
    storageBucket: 'project-8a903.firebasestorage.app',
    iosClientId: '513756595410-qhd3rklb9780kj1cjthahtg741l6icc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6HjdyuU8wX4tuHnPqg7nt2sUa-aNGeY',
    appId: '1:513756595410:ios:93f2407d1084060d4b590b',
    messagingSenderId: '513756595410',
    projectId: 'project-8a903',
    storageBucket: 'project-8a903.firebasestorage.app',
    iosClientId: '513756595410-qhd3rklb9780kj1cjthahtg741l6icc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_tHGk1N9HgPC02oymF2rs3qEhducT_rg',
    appId: '1:513756595410:web:2c3a279c017fe2d04b590b',
    messagingSenderId: '513756595410',
    projectId: 'project-8a903',
    authDomain: 'project-8a903.firebaseapp.com',
    storageBucket: 'project-8a903.firebasestorage.app',
    measurementId: 'G-72LQSPQWEP',
  );

}